package transit

type AutoGenerated struct {
	Siri Siri `json:"Siri"`
}
type Location struct {
	Longitude string `json:"Longitude"`
	Latitude  string `json:"Latitude"`
}
type Centroid struct {
	Location Location `json:"Location"`
}
type AccessibilityLimitation struct {
	WheelchairAccess string `json:"WheelchairAccess"`
}
type Limitations struct {
	AccessibilityLimitation AccessibilityLimitation `json:"AccessibilityLimitation"`
}
type AccessibilityAssessment struct {
	Version                string      `json:"@version"`
	ID                     string      `json:"@id"`
	MobilityImpairedAccess string      `json:"MobilityImpairedAccess"`
	Limitations            Limitations `json:"limitations"`
}
type PostalAddress struct {
	AddressLine1 string `json:"AddressLine1"`
	Town         string `json:"Town"`
}
type OperatorRef struct {
	Ref string `json:"@ref"`
}
type ParkingRef struct {
	Ref string `json:"@ref"`
}
type AdjacentSites struct {
	ParkingRef ParkingRef `json:"ParkingRef"`
}
type Quay struct {
	CompassOctant string `json:"CompassOctant"`
}
type Quays struct {
	Quay Quay `json:"Quay"`
}
type StopPlace struct {
	Version                 string                  `json:"@version"`
	ID                      string                  `json:"@id"`
	Name                    string                  `json:"Name"`
	Description             interface{}             `json:"Description"`
	Centroid                Centroid                `json:"Centroid"`
	AccessibilityAssessment AccessibilityAssessment `json:"AccessibilityAssessment"`
	PostalAddress           PostalAddress           `json:"PostalAddress"`
	OperatorRef             OperatorRef             `json:"OperatorRef"`
	AdjacentSites           AdjacentSites           `json:"adjacentSites"`
	PublicCode              string                  `json:"PublicCode"`
	TransportMode           string                  `json:"TransportMode"`
	StopPlaceType           string                  `json:"StopPlaceType"`
	Quays                   Quays                   `json:"quays,omitempty"`
}
type StopPlaces struct {
	StopPlace []StopPlace `json:"StopPlace"`
}
type SiteFrame struct {
	Version    string      `json:"@version"`
	ID         string      `json:"@id"`
	StopPlaces StopPlaces  `json:"stopPlaces"`
	Parkings   interface{} `json:"parkings"`
}
type DataObjects struct {
	SiteFrame SiteFrame `json:"SiteFrame"`
}
type DataObjectDelivery struct {
	ResponseTimestamp string      `json:"ResponseTimestamp"`
	DataObjects       DataObjects `json:"dataObjects"`
}
type ServiceDelivery struct {
	ResponseTimestamp  string             `json:"ResponseTimestamp"`
	DataObjectDelivery DataObjectDelivery `json:"DataObjectDelivery"`
}
type Siri struct {
	ServiceDelivery ServiceDelivery `json:"ServiceDelivery"`
}
